### PR TITLE
resolves #90: using sync to coordinate error passing in projects polling

### LINKED ISSUE #90: panic: send on closed channel
@inge4pres, I was running some tests with a master build locally and ran into the following error:

```
panic: send on closed channel

goroutine 41 [running]:
github.com/mvisonneau/gitlab-ci-pipelines-exporter/cmd.(*Client).pollProjectsWith.func1(0xc000192480, 0xc0000f61e0, 0xc00012fd00, 0xc000192780)
	/go/gitlab-ci-pipelines-exporter/cmd/gitlab.go:483 +0x1b2
created by github.com/mvisonneau/gitlab-ci-pipelines-exporter/cmd.(*Client).pollProjectsWith
	/go/gitlab-ci-pipelines-exporter/cmd/gitlab.go:476 +0x120
```

I'll try to dig into it later on, just to let you know! :)

nb: probably related to https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/pull/88

### PR DESCRIPTION
**Pull request by inge4pres**
Here a correction to the previous impementation of concurrent polling mentioned in #88 but that caused #90 due to missing coordination on closing the channel.
Added a `sync.Waitgroup` to let the polling goroutines complete sending the error before closing the output channel.
Improved the signature of the method to make it testable in isolation

### CODE REVIEW

File: cmd/gitlab_test.go [hunk 1]
```diff
@@ -227,3 +227,22 @@ func pollingResult(until <-chan struct{}, projects <-chan Project, client *Clien
...
 	return numErrs
 }
+
+func TestClient_pollProjectsWith(t *testing.T) {
+	c := Client{}
+	message := "some error"
+	doing := func(Project) error {
+		return fmt.Errorf(message)
+	}
+	testProjects := []Project{{Name: "test"}, {Name: "test2"}, {Name: "test4"}, {Name: "test4"}}
```
Comment (mvisonneau) [inline cmd/gitlab_test.go:237]:
```suggestion
	testProjects := []Project{{Name: "test"}, {Name: "test2"}, {Name: "test3"}, {Name: "test4"}}
```

File: cmd/gitlab.go [hunk 2]
```diff
@@ -466,40 +469,39 @@ func (c *Client) findProjectsFromWildcards() error {
...
 
-func (c *Client) pollProjectsWith(numWorkers int, until <-chan struct{}, projects ...Project) []error {
-	var errs []error
+func (c *Client) pollProjectsWith(numWorkers int, doing func(Project) error, until <-chan struct{}, on ...Project) <-chan error {
 	errorStream := make(chan error)
-	defer close(errorStream)
-	projectsToPoll := make(chan Project, len(projects))
+	projectsToPoll := make(chan Project, len(on))
+	// sync closing the error channel via a waitGroup
+	wg := sync.WaitGroup{}
```
Comment (mvisonneau) [inline cmd/gitlab.go:476]:
```suggestion
	wg := new(sync.WaitGroup)
```

File: cmd/gitlab.go [hunk 3]
```diff
@@ -466,40 +469,39 @@ func (c *Client) findProjectsFromWildcards() error {
...
 					return
-				case p := <-projectsToPoll:
-					if e := c.pollProject(p); e != nil {
-						errorStream <- e
-					}
+				case errorStream <- doing(p):
 				}
 			}
-		}()
+		}(&wg)
```
Comment (mvisonneau) [inline cmd/gitlab.go:490]:
```suggestion
		}(wg)
```

File: cmd/gitlab_test.go (hunk 1 above)
Comment (inge4pres) [reply cmd/gitlab_test.go:237]: ah 👍

File: cmd/gitlab.go (hunk 2 above)
Comment (inge4pres) [reply cmd/gitlab.go:476]: `new()`has never been used in the codebase, plus I prefer not to use it at all in any of my projects in favour of `&T{}` or `var X T` for initialisation.
The reason for doing this is having a consistent readability across codebases.
So I'd use `var wg sync.WaitGroup` here, because we adopted it elsewhere in the project.

File: cmd/gitlab.go (hunk 3 above)
Comment (inge4pres) [reply cmd/gitlab.go:490]: Tied to [above](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/pull/91#discussion_r411925141) we really need to pass a pointer here or the `wg.Done()` will have a wrong behaviour.
So if you don't like passing the address in the closure, we can implement the suggested code and initialise the variable as `wg := &sync.WaitGroup{}`.

File: cmd/gitlab.go (hunk 2 above)
Comment (mvisonneau) [reply cmd/gitlab.go:476]: sounds good 👍

**Comment by inge4pres** [comment]
So I actually didn't push the last commit with the suggested fixes, I'll try pushing here again

**Comment by mvisonneau** [comment]
no worries I'll update it later on 👍
